---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

# opsgenie setup.
- name: Copy oec configuration in place.
  template:
    src: "{{ oec_conf_template }}"
    dest: "{{ oec_conf_file_path }}"
    owner: opsgenie
    group: opsgenie
    mode: 0644
  notify:
    - reload edge

- name: Ensure Edge Connector is started and enabled to start at boot.
  service: name=oec state=started enabled=yes
